# Generated by Django 4.0.6 on 2022-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.BooleanField(default=False)),
                ('mp', models.BooleanField(default=False)),
            ],
        ),
    ]
